import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:uuid/uuid.dart';

abstract class ParticipantApi { Future<Map<String,dynamic>> exchange(String invitation); Future<Map<String,dynamic>> session(); Future<void> consent(); Future<void> logout(); }
class ApiError implements Exception { const ApiError(this.message); final String message; }
class Api implements ParticipantApi {
  Api(this.base,this.token); final Uri base; final String? token;
  // ignore: use_null_aware_elements
  Future<Map<String,dynamic>> request(String method,String path,{Object? body,String? idempotencyKey}) async { if(base.scheme!='https') throw const ApiError('A secure HTTPS address is required.'); final r=http.Request(method,base.resolve(path))..headers.addAll({'Accept':'application/json','Content-Type':'application/json',if(token case final value?) 'Authorization':'Bearer $value',if(idempotencyKey case final key?) 'Idempotency-Key':key})..body=body==null?'':jsonEncode(body); final x=await http.Response.fromStream(await r.send()); if(x.statusCode==401) throw const ApiError('Your session has ended.'); if(x.statusCode<200||x.statusCode>299) throw const ApiError('We could not complete that safely. Please try again.'); return Map<String,dynamic>.from(jsonDecode(x.body)); }
  @override Future<Map<String,dynamic>> exchange(String invitation)=>request('POST','/api/v1/participant/session/exchange',body:{'invitation_token':invitation});
  @override Future<Map<String,dynamic>> session()=>request('GET','/api/v1/participant/session');
  @override Future<void> consent() async { await request('POST','/api/v1/participant/consent',body:{'consent':true}); }
  @override Future<void> logout() async { await request('DELETE','/api/v1/participant/session'); }
  Future<List<dynamic>> activities() async => (await request('GET','/api/v1/participant/activities'))['data'] as List<dynamic>;
  Future<void> draft(int id,String answer,String key) async { await request('PUT','/api/v1/participant/activities/$id/draft',body:{'answer':answer,'choices':[]},idempotencyKey:key); }
  Future<void> submit(int id,String answer,String key) async { await request('POST','/api/v1/participant/activities/$id/submit',body:{'answer':answer,'choices':[]},idempotencyKey:key); }
}
class SessionStore { SessionStore(this.storage); final FlutterSecureStorage storage; Future<void> save(String url,String token)=>Future.wait([storage.write(key:'api_url',value:url),storage.write(key:'access_token',value:token)]); Future<(String,String)?> read() async { final u=await storage.read(key:'api_url');final t=await storage.read(key:'access_token');return u==null||t==null?null:(u,t); } Future<void> clear()=>storage.deleteAll(); }
final _store=SessionStore(FlutterSecureStorage());
void main()=>runApp(ParticipantApp());
class ParticipantApp extends StatefulWidget { ParticipantApp({super.key,SessionStore? store,this.factory}):store=store??_store; final SessionStore store; final ParticipantApi Function(String,String?)? factory; @override State<ParticipantApp> createState()=>_ParticipantAppState(); }
class _ParticipantAppState extends State<ParticipantApp> { ParticipantApi? api; Map<String,dynamic>? session; bool busy=true; String? error;
  ParticipantApi make(String u,String? t)=>widget.factory?.call(u,t)??Api(Uri.parse(u),t);
  @override void initState(){super.initState();restore();}
  Future<void> restore() async { final saved=await widget.store.read(); if(saved!=null){try{api=make(saved.$1,saved.$2);session=await api!.session();}catch(_){await widget.store.clear();api=null;}}if(mounted)setState(()=>busy=false); }
  Future<void> join(String url,String invitation) async { try{final first=make(url,null);final result=await first.exchange(invitation);final token=(result['session'] as Map)['access_token'] as String;await widget.store.save(url,token);api=make(url,token);session=await api!.session();error=null;} on ApiError catch(e){error=e.message;}catch(_){error='We could not connect. Please check your details and try again.';}if(mounted)setState((){}); }
  Future<void> accept() async { try{await api!.consent();session=await api!.session();error=null;}on ApiError catch(e){error=e.message;}if(mounted)setState((){}); }
  Future<void> signOut() async { try{await api?.logout();}catch(_){}await widget.store.clear();if(mounted)setState((){api=null;session=null;error=null;}); }
  @override Widget build(BuildContext c){if(busy)return const MaterialApp(home:Scaffold(body:Center(child:CircularProgressIndicator(semanticsLabel:'Loading your secure session'))));if(api==null)return MaterialApp(home:Invite(error:error,onJoin:join));final participant=Map<String,dynamic>.from(session!['participant']);if(participant['consent_status']!='granted')return MaterialApp(home:Consent(error:error,onAccept:accept));return MaterialApp(home:Home(api:api! as Api,name:participant['display_name'] as String,onLogout:signOut));}
}
class Invite extends StatefulWidget { const Invite({super.key,required this.error,required this.onJoin});final String? error;final Future<void> Function(String,String) onJoin;@override State<Invite> createState()=>_InviteState();}
class _InviteState extends State<Invite>{final url=TextEditingController(),code=TextEditingController();bool waiting=false;Future<void> submit()async{setState(()=>waiting=true);await widget.onJoin(url.text.trim(),code.text.trim());if(mounted)setState(()=>waiting=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Citizen Centric')),body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Semantics(header:true,child:const Text('Join your study',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const SizedBox(height:12),const Text('Enter the secure service address and invitation code from your research team.'),TextField(controller:url,keyboardType:TextInputType.url,decoration:const InputDecoration(labelText:'Secure service address',hintText:'https://…')),TextField(controller:code,decoration:const InputDecoration(labelText:'Invitation code')),if(widget.error!=null)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.only(top:12),child:Text(widget.error!,style:const TextStyle(color:Colors.red)))),const SizedBox(height:20),SizedBox(height:48,child:FilledButton(onPressed:waiting?null:submit,child:Text(waiting?'Checking invitation…':'Continue')))]))));}
class Consent extends StatefulWidget{const Consent({super.key,required this.error,required this.onAccept});final String? error;final Future<void> Function()onAccept;@override State<Consent>createState()=>_ConsentState();}class _ConsentState extends State<Consent>{bool yes=false,waiting=false;Future<void>go()async{setState(()=>waiting=true);await widget.onAccept();if(mounted)setState(()=>waiting=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Your consent')),body:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Semantics(header:true,child:const Text('Before you begin',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const Text('Taking part is your choice. Your responses are shared securely with the Citizen Centric research team for this study.'),CheckboxListTile(value:yes,onChanged:(v)=>setState(()=>yes=v??false),title:const Text('I understand and agree to take part.'),controlAffinity:ListTileControlAffinity.leading),if(widget.error!=null)Semantics(liveRegion:true,child:Text(widget.error!,style:const TextStyle(color:Colors.red))),SizedBox(height:48,child:FilledButton(onPressed:yes&&!waiting?go:null,child:Text(waiting?'Saving consent…':'Accept and continue')))])));}
class Home extends StatelessWidget{const Home({super.key,required this.api,required this.name,required this.onLogout});final Api api;final String name;final Future<void>Function()onLogout;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Your study'),actions:[IconButton(tooltip:'Sign out',onPressed:onLogout,icon:const Icon(Icons.logout))]),body:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Semantics(header:true,child:Text('Welcome, $name',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const SizedBox(height:12),const Text('You are ready to take part.'),const SizedBox(height:24),Card(child:ListTile(title:const Text('Activities'),subtitle:const Text('View and respond to activities'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Activities(api:api)))))])));}

class Queue { static Future<void> add(Map<String,dynamic> entry) async { final p=await SharedPreferences.getInstance();final rows=(p.getStringList('submission_queue')??[]);rows.add(jsonEncode(entry));await p.setStringList('submission_queue',rows); } static Future<int> count()async=>(await SharedPreferences.getInstance()).getStringList('submission_queue')?.length??0; }
class Activities extends StatefulWidget{const Activities({super.key,required this.api});final Api api;@override State<Activities>createState()=>_ActivitiesState();}class _ActivitiesState extends State<Activities>{late Future<List<dynamic>> load;@override void initState(){super.initState();load=widget.api.activities();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Activities')),body:FutureBuilder<List<dynamic>>(future:load,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator(semanticsLabel:'Loading activities'));if(s.hasError)return Center(child:FilledButton(onPressed:()=>setState(()=>load=widget.api.activities()),child:const Text('Try again')));final rows=s.data??[];if(rows.isEmpty)return const Center(child:Text('There are no activities to complete right now.'));return RefreshIndicator(onRefresh:()async=>setState(()=>load=widget.api.activities()),child:ListView(children:rows.map((r)=>ListTile(title:Text(r['title']??'Activity'),subtitle:Text(r['availability']?['status']??'Available'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>TextActivity(api:widget.api,item:Map<String,dynamic>.from(r)))))).toList()));}));}
class TextActivity extends StatefulWidget{const TextActivity({super.key,required this.api,required this.item});final Api api;final Map<String,dynamic>item;@override State<TextActivity>createState()=>_TextActivityState();}class _TextActivityState extends State<TextActivity>{final text=TextEditingController();bool working=false;String status='';String get key=>'draft_${widget.item['activity_id']}';@override void initState(){super.initState();restore();}Future<void>restore()async{text.text=(await SharedPreferences.getInstance()).getString(key)??'';}Future<void>save(bool submit)async{setState(()=>working=true);final id=const Uuid().v4();final p=await SharedPreferences.getInstance();await p.setString(key,text.text);try{if(submit){await widget.api.submit(widget.item['activity_id'] as int,text.text,id);await p.remove(key);status='Submitted successfully.';}else{await widget.api.draft(widget.item['activity_id'] as int,text.text,id);status='Draft saved.';}}catch(_){await Queue.add({'activity_id':widget.item['activity_id'],'answer':text.text,'idempotency_key':id,'attempts':0});status='Saved on this device. We will retry when you reconnect.';}if(mounted)setState(()=>working=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.item['title']??'Activity')),body:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(widget.item['prompt']??'Share your response.'),const SizedBox(height:12),Expanded(child:TextField(controller:text,maxLines:null,expands:true,decoration:const InputDecoration(labelText:'Your response',border:OutlineInputBorder()))),if(status.isNotEmpty)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.all(8),child:Text(status))),OutlinedButton(onPressed:working?null:()=>save(false),child:const Text('Save draft')),SizedBox(height:48,child:FilledButton(onPressed:working?null:()=>save(true),child:Text(working?'Saving…':'Submit response')))])));}
