import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:uuid/uuid.dart';
import 'package:image_picker/image_picker.dart';
import 'package:file_picker/file_picker.dart';
import 'package:record/record.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:path_provider/path_provider.dart';

abstract class ParticipantApi { Future<Map<String,dynamic>> exchange(String invitation); Future<Map<String,dynamic>> session(); Future<void> consent(); Future<void> logout(); }
class ApiError implements Exception { const ApiError(this.message); final String message; }
const _allowLocalQaHttp = bool.fromEnvironment('PCIP_LOCAL_QA');
bool allowsApiBase(Uri base) => base.scheme == 'https' || (kDebugMode && _allowLocalQaHttp && base.scheme == 'http' && (base.host == 'localhost' || base.host == '10.0.2.2'));
String participantDateTime(Object? value) { final parsed=DateTime.tryParse(value?.toString()??''); if(parsed==null)return 'Date unavailable'; final local=parsed.toLocal(); String two(int number)=>number.toString().padLeft(2,'0'); return '${two(local.day)}/${two(local.month)}/${local.year} at ${two(local.hour)}:${two(local.minute)}'; }
class Api implements ParticipantApi {
  Api(this.base,this.token); final Uri base; final String? token;
  // ignore: use_null_aware_elements
  Future<Map<String,dynamic>> request(String method,String path,{Object? body,String? idempotencyKey}) async { if(!allowsApiBase(base)) throw const ApiError('A secure HTTPS address is required.'); final r=http.Request(method,base.resolve(path))..headers.addAll({'Accept':'application/json','Content-Type':'application/json',if(token case final value?) 'Authorization':'Bearer $value',if(idempotencyKey case final key?) 'Idempotency-Key':key})..body=body==null?'':jsonEncode(body); final x=await http.Response.fromStream(await r.send()); if(x.statusCode==401) throw const ApiError('Your session has ended.'); if(x.statusCode<200||x.statusCode>299) throw const ApiError('We could not complete that safely. Please try again.'); return Map<String,dynamic>.from(jsonDecode(x.body)); }
  @override Future<Map<String,dynamic>> exchange(String invitation)=>request('POST','/api/v1/participant/session/exchange',body:{'invitation_token':invitation});
  @override Future<Map<String,dynamic>> session()=>request('GET','/api/v1/participant/session');
  @override Future<void> consent() async { await request('POST','/api/v1/participant/consent',body:{'consent':true}); }
  @override Future<void> logout() async { await request('DELETE','/api/v1/participant/session'); }
  Future<List<dynamic>> activities() async => (await request('GET','/api/v1/participant/activities'))['data'] as List<dynamic>;
  Future<void> draft(int id,String answer,String key) async { await request('PUT','/api/v1/participant/activities/$id/draft',body:{'answer':answer,'choices':[]},idempotencyKey:key); }
  Future<void> submit(int id,String answer,String key) async { await request('POST','/api/v1/participant/activities/$id/submit',body:{'answer':answer,'choices':[]},idempotencyKey:key); }
  Future<Map<String,dynamic>> profile() => request('GET','/api/v1/participant/profile');
  Future<Map<String,dynamic>> updatePreference(String value,String key) => request('PUT','/api/v1/participant/profile',body:{'communication_preference':value},idempotencyKey:key);
  Future<List<dynamic>> history() async => (await request('GET','/api/v1/participant/submissions'))['data'] as List<dynamic>;
  Future<List<dynamic>> messages() async => (await request('GET','/api/v1/participant/messages'))['data'] as List<dynamic>;
  Future<Map<String,dynamic>> sendMessage(String body,String key) => request('POST','/api/v1/participant/messages',body:{'body':body},idempotencyKey:key);
  Future<Map<String,dynamic>> uploadPhoto(int activityId,XFile photo,String key) async { final r=http.MultipartRequest('POST',base.resolve('/api/v1/participant/activities/$activityId/evidence-uploads'))..headers.addAll({'Accept':'application/json',if(token case final value?)'Authorization':'Bearer $value','Idempotency-Key':key})..fields['activity_id']='$activityId'..files.add(await http.MultipartFile.fromPath('file',photo.path,filename:photo.name));final x=await http.Response.fromStream(await r.send());if(x.statusCode==401)throw const ApiError('Your session has ended.');if(x.statusCode<200||x.statusCode>299)throw const ApiError('We could not upload that photo. Please try again.');return Map<String,dynamic>.from(jsonDecode(x.body));}
  Future<Map<String,dynamic>> evidenceStatus(int id)=>request('GET','/api/v1/participant/evidence/$id/status');
  Future<Map<String,dynamic>> uploadDocument(int activityId,String path,String name,String key) async { final r=http.MultipartRequest('POST',base.resolve('/api/v1/participant/activities/$activityId/evidence-uploads'))..headers.addAll({'Accept':'application/json',if(token case final value?)'Authorization':'Bearer $value','Idempotency-Key':key})..fields['activity_id']='$activityId'..files.add(await http.MultipartFile.fromPath('file',path,filename:name));final x=await http.Response.fromStream(await r.send());if(x.statusCode==401)throw const ApiError('Your session has ended.');if(x.statusCode<200||x.statusCode>299)throw const ApiError('We could not upload that document. Please try again.');return Map<String,dynamic>.from(jsonDecode(x.body));}
  Future<Map<String,dynamic>> uploadAudio(int activityId,String path,String key)=>uploadDocument(activityId,path,'voice-diary.m4a',key);
  Future<Map<String,dynamic>> withdraw(String key)=>request('POST','/api/v1/participant/privacy/withdrawal-requests',body:{'scope':'study'},idempotencyKey:key);
  Future<Map<String,dynamic>> deletion(String key)=>request('POST','/api/v1/participant/privacy/deletion-requests',body:{'mode_preference':'auto'},idempotencyKey:key);
}
Future<void> clearParticipantCache(SharedPreferences prefs) async { final sensitive=prefs.getKeys().where((key)=>key=='cached_profile'||key=='cached_history'||key=='cached_messages'||key=='submission_queue'||key.startsWith('draft_')).toList(); for(final key in sensitive){await prefs.remove(key);} }
Future<Map<String,dynamic>?> cachedObject(String key) async { final prefs=await SharedPreferences.getInstance(); final value=prefs.getString(key); if(value==null)return null; try{final decoded=jsonDecode(value);if(decoded is Map)return Map<String,dynamic>.from(decoded);}catch(_){}await prefs.remove(key);return null; }
Future<List<dynamic>?> cachedList(String key) async { final prefs=await SharedPreferences.getInstance(); final value=prefs.getString(key); if(value==null)return null; try{final decoded=jsonDecode(value);if(decoded is List)return decoded;}catch(_){}await prefs.remove(key);return null; }
class SessionStore { SessionStore(this.storage); final FlutterSecureStorage storage; Future<void> save(String url,String token)=>Future.wait([storage.write(key:'api_url',value:url),storage.write(key:'access_token',value:token)]); Future<(String,String)?> read() async { final u=await storage.read(key:'api_url');final t=await storage.read(key:'access_token');return u==null||t==null?null:(u,t); } Future<void> clear() async { await storage.deleteAll(); await clearParticipantCache(await SharedPreferences.getInstance()); } }
final _store=SessionStore(FlutterSecureStorage());
void main()=>runApp(ParticipantApp());
class ParticipantApp extends StatefulWidget { ParticipantApp({super.key,SessionStore? store,this.factory}):store=store??_store; final SessionStore store; final ParticipantApi Function(String,String?)? factory; @override State<ParticipantApp> createState()=>_ParticipantAppState(); }
class _ParticipantAppState extends State<ParticipantApp> { ParticipantApi? api; Map<String,dynamic>? session; bool busy=true; String? error;
  ParticipantApi make(String u,String? t)=>widget.factory?.call(u,t)??Api(Uri.parse(u),t);
  @override void initState(){super.initState();restore();}
  Future<void> restore() async { final saved=await widget.store.read(); if(saved!=null){try{api=make(saved.$1,saved.$2);session=await api!.session();}catch(_){await widget.store.clear();api=null;}}if(mounted)setState(()=>busy=false); }
  Future<void> join(String url,String invitation) async { try{final first=make(url,null);final result=await first.exchange(invitation);final token=(result['session'] as Map)['access_token'] as String;await widget.store.save(url,token);api=make(url,token);session=await api!.session();error=null;} on ApiError catch(e){error=e.message;}catch(_){error='We could not connect. Please check your details and try again.';}if(mounted)setState((){}); }
  Future<void> accept() async { try{await api!.consent();session=await api!.session();error=null;}on ApiError catch(e){error=e.message;}if(mounted)setState((){}); }
  Future<void> signOut() async { try{await api?.logout();}catch(_){}await widget.store.clear();if(mounted)setState((){api=null;session=null;error=null;}); }
  @override Widget build(BuildContext c){if(busy)return const MaterialApp(home:Scaffold(body:Center(child:CircularProgressIndicator(semanticsLabel:'Loading your secure session'))));if(api==null)return MaterialApp(home:Invite(error:error,onJoin:join));final participant=Map<String,dynamic>.from(session!['participant']);if(participant['consent_status']!='granted')return MaterialApp(home:Consent(error:error,onAccept:accept));return MaterialApp(home:Home(api:api! as Api,name:participant['display_name'] as String,onLogout:signOut));}
}
class Invite extends StatefulWidget { const Invite({super.key,required this.error,required this.onJoin});final String? error;final Future<void> Function(String,String) onJoin;@override State<Invite> createState()=>_InviteState();}
class _InviteState extends State<Invite>{final url=TextEditingController(),code=TextEditingController();bool waiting=false;Future<void> submit()async{setState(()=>waiting=true);await widget.onJoin(url.text.trim(),code.text.trim());if(mounted)setState(()=>waiting=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Citizen Centric')),body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Semantics(header:true,child:const Text('Join your study',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const SizedBox(height:12),const Text('Enter the secure service address and invitation code from your research team.'),TextField(controller:url,keyboardType:TextInputType.url,decoration:const InputDecoration(labelText:'Secure service address',hintText:'https://…')),TextField(controller:code,decoration:const InputDecoration(labelText:'Invitation code')),if(widget.error!=null)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.only(top:12),child:Text(widget.error!,style:const TextStyle(color:Colors.red)))),const SizedBox(height:20),SizedBox(height:48,child:FilledButton(onPressed:waiting?null:submit,child:Text(waiting?'Checking invitation…':'Continue')))]))));}
class Consent extends StatefulWidget{const Consent({super.key,required this.error,required this.onAccept});final String? error;final Future<void> Function()onAccept;@override State<Consent>createState()=>_ConsentState();}class _ConsentState extends State<Consent>{bool yes=false,waiting=false;Future<void>go()async{setState(()=>waiting=true);await widget.onAccept();if(mounted)setState(()=>waiting=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Your consent')),body:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Semantics(header:true,child:const Text('Before you begin',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const Text('Taking part is your choice. Your responses are shared securely with the Citizen Centric research team for this study.'),CheckboxListTile(value:yes,onChanged:(v)=>setState(()=>yes=v??false),title:const Text('I understand and agree to take part.'),controlAffinity:ListTileControlAffinity.leading),if(widget.error!=null)Semantics(liveRegion:true,child:Text(widget.error!,style:const TextStyle(color:Colors.red))),SizedBox(height:48,child:FilledButton(onPressed:yes&&!waiting?go:null,child:Text(waiting?'Saving consent…':'Accept and continue')))])));}
class Home extends StatelessWidget{const Home({super.key,required this.api,required this.name,required this.onLogout});final Api api;final String name;final Future<void>Function()onLogout;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Your study'),actions:[IconButton(tooltip:'Sign out',onPressed:onLogout,icon:const Icon(Icons.logout))]),body:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Semantics(header:true,child:Text('Welcome, $name',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const SizedBox(height:12),const Text('You are ready to take part.'),const SizedBox(height:24),Card(child:ListTile(title:const Text('Activities'),subtitle:const Text('View and respond to activities'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Activities(api:api))))),Card(child:ListTile(title:const Text('Profile and contact preferences'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Profile(api:api))))),Card(child:ListTile(title:const Text('Submission history'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>History(api:api))))),Card(child:ListTile(title:const Text('Messages'),subtitle:const Text('Messages from your research team'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Messages(api:api))))),Card(child:ListTile(title:const Text('Privacy choices'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PrivacyChoices(api:api)))))])));}

enum SyncState { waiting, sending, sent, needsAttention }
class Queue {
  static const _key='submission_queue';
  static Future<void> add(Map<String,dynamic> entry) async { final p=await SharedPreferences.getInstance();final rows=p.getStringList(_key)??[];if(rows.any((row)=>jsonDecode(row)['idempotency_key']==entry['idempotency_key']))return;rows.add(jsonEncode({...entry,'attempts':0,'next_attempt_at':DateTime.now().toIso8601String()}));await p.setStringList(_key,rows); }
  static Future<int> count()async=>(await SharedPreferences.getInstance()).getStringList(_key)?.length??0;
  static Duration backoff(int attempts)=>Duration(seconds:(1<<attempts.clamp(0,6)));
  static Future<SyncState> replay(Api api,{DateTime? now}) async { final p=await SharedPreferences.getInstance();final rows=p.getStringList(_key)??[];final retained=<String>[];var state=SyncState.sent;final clock=now??DateTime.now();for(final row in rows){Map<String,dynamic> item;try{item=Map<String,dynamic>.from(jsonDecode(row));}catch(_){retained.add(row);state=SyncState.needsAttention;continue;}final due=DateTime.tryParse(item['next_attempt_at']??'')??clock;if(due.isAfter(clock)){retained.add(row);state=SyncState.waiting;continue;}try{await api.submit(item['activity_id'] as int,item['answer'] as String,item['idempotency_key'] as String);}on ApiError catch(e){if(e.message=='Your session has ended.'){retained.add(row);state=SyncState.needsAttention;}else{final attempts=(item['attempts'] as int? ??0)+1;item['attempts']=attempts;item['next_attempt_at']=clock.add(backoff(attempts)).toIso8601String();retained.add(jsonEncode(item));state=SyncState.waiting;}}catch(_){final attempts=(item['attempts'] as int? ??0)+1;item['attempts']=attempts;item['next_attempt_at']=clock.add(backoff(attempts)).toIso8601String();retained.add(jsonEncode(item));state=SyncState.waiting;}}await p.setStringList(_key,retained);return state; }
}
class Activities extends StatefulWidget{const Activities({super.key,required this.api});final Api api;@override State<Activities>createState()=>_ActivitiesState();}class _ActivitiesState extends State<Activities> with WidgetsBindingObserver{late Future<List<dynamic>> load;SyncState sync=SyncState.sent;@override void initState(){super.initState();WidgetsBinding.instance.addObserver(this);load=widget.api.activities();replay();}@override void dispose(){WidgetsBinding.instance.removeObserver(this);super.dispose();}@override void didChangeAppLifecycleState(AppLifecycleState s){if(s==AppLifecycleState.resumed)replay();}Future<void>replay()async{setState(()=>sync=SyncState.sending);final result=await Queue.replay(widget.api);if(mounted)setState(()=>sync=result);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Activities')),body:FutureBuilder<List<dynamic>>(future:load,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator(semanticsLabel:'Loading activities'));if(s.hasError)return Center(child:FilledButton(onPressed:()=>setState(()=>load=widget.api.activities()),child:const Text('Try again')));final rows=s.data??[];if(rows.isEmpty)return const Center(child:Text('There are no activities to complete right now.'));final label={SyncState.waiting:'Saved on this device — waiting to send',SyncState.sending:'Sending saved responses…',SyncState.sent:'',SyncState.needsAttention:'Saved responses need attention. Please sign in again.'}[sync]!;return RefreshIndicator(onRefresh:()async{await replay();setState(()=>load=widget.api.activities());},child:ListView(children:[if(label.isNotEmpty)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.all(12),child:Text(label))),...rows.map((r)=>ListTile(title:Text(r['title']??'Activity'),subtitle:Text(r['availability']?['status']??'Available'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>TextActivity(api:widget.api,item:Map<String,dynamic>.from(r))))))]));}));}
class TextActivity extends StatefulWidget{const TextActivity({super.key,required this.api,required this.item});final Api api;final Map<String,dynamic>item;@override State<TextActivity>createState()=>_TextActivityState();}class _TextActivityState extends State<TextActivity>{final text=TextEditingController();bool working=false;String status='';String get key=>'draft_${widget.item['activity_id']}';@override void initState(){super.initState();restore();}Future<void>restore()async{text.text=(await SharedPreferences.getInstance()).getString(key)??'';}Future<void>save(bool submit)async{setState(()=>working=true);final id=const Uuid().v4();final p=await SharedPreferences.getInstance();await p.setString(key,text.text);try{if(submit){await widget.api.submit(widget.item['activity_id'] as int,text.text,id);await p.remove(key);status='Submitted successfully.';}else{await widget.api.draft(widget.item['activity_id'] as int,text.text,id);status='Draft saved.';}}catch(_){await Queue.add({'activity_id':widget.item['activity_id'],'answer':text.text,'idempotency_key':id,'attempts':0});status='Saved on this device. We will retry when you reconnect.';}if(mounted)setState(()=>working=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.item['title']??'Activity'),actions:[IconButton(tooltip:'Add photo',icon:const Icon(Icons.add_a_photo),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PhotoEvidence(api:widget.api,activityId:widget.item['activity_id'] as int)))),IconButton(tooltip:'Add document',icon:const Icon(Icons.attach_file),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DocumentEvidence(api:widget.api,activityId:widget.item['activity_id'] as int)))),IconButton(tooltip:'Record voice diary',icon:const Icon(Icons.mic),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>VoiceDiary(api:widget.api,activityId:widget.item['activity_id'] as int))))]),body:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(widget.item['prompt']??'Share your response.'),const SizedBox(height:12),Expanded(child:TextField(controller:text,maxLines:null,expands:true,decoration:const InputDecoration(labelText:'Your response',border:OutlineInputBorder()))),if(status.isNotEmpty)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.all(8),child:Text(status))),OutlinedButton(onPressed:working?null:()=>save(false),child:const Text('Save draft')),SizedBox(height:48,child:FilledButton(onPressed:working?null:()=>save(true),child:Text(working?'Saving…':'Submit response')))])));}

class Profile extends StatefulWidget{const Profile({super.key,required this.api});final Api api;@override State<Profile>createState()=>_ProfileState();}class _ProfileState extends State<Profile>{late Future<Map<String,dynamic>> load;String? message;@override void initState(){super.initState();load=read();}Future<Map<String,dynamic>>read()async{try{final p=await widget.api.profile();(await SharedPreferences.getInstance()).setString('cached_profile',jsonEncode(p));return p;}catch(_){final cached=await cachedObject('cached_profile');if(cached!=null)return cached;rethrow;}}Future<void>save(String v)async{try{final p=await widget.api.updatePreference(v,const Uuid().v4());(await SharedPreferences.getInstance()).setString('cached_profile',jsonEncode(p));if(mounted)setState(()=>message='Your preference has been saved.');}catch(_){if(mounted)setState(()=>message='We could not save that change. Please try again.');}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Profile')),body:FutureBuilder<Map<String,dynamic>>(future:load,builder:(c,s){if(!s.hasData){if(s.hasError)return Center(child:FilledButton(onPressed:()=>setState(()=>load=read()),child:const Text('Try again')));return const Center(child:CircularProgressIndicator(semanticsLabel:'Loading profile'));}final p=s.data!;return RefreshIndicator(onRefresh:()async=>setState(()=>load=read()),child:ListView(padding:const EdgeInsets.all(20),children:[Semantics(header:true,child:Text(p['display_name']??'Your profile',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const SizedBox(height:20),DropdownButtonFormField<String>(initialValue:p['communication_preference'],decoration:const InputDecoration(labelText:'How should we contact you?'),items:const ['email','sms','phone','none'].map((v)=>DropdownMenuItem(value:v,child:Text(v=='none'?'Do not contact me':v.toUpperCase()))).toList(),onChanged:(v){if(v!=null)save(v);}),if(message!=null)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.only(top:12),child:Text(message!)))]));}));}
class History extends StatefulWidget{const History({super.key,required this.api});final Api api;@override State<History>createState()=>_HistoryState();}class _HistoryState extends State<History>{late Future<List<dynamic>>load;@override void initState(){super.initState();load=read();}Future<List<dynamic>>read()async{try{final rows=await widget.api.history();(await SharedPreferences.getInstance()).setString('cached_history',jsonEncode(rows));return rows;}catch(_){final cached=await cachedList('cached_history');if(cached!=null)return cached;rethrow;}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Submission history')),body:FutureBuilder<List<dynamic>>(future:load,builder:(c,s){if(!s.hasData){if(s.hasError)return Center(child:FilledButton(onPressed:()=>setState(()=>load=read()),child:const Text('Try again')));return const Center(child:CircularProgressIndicator(semanticsLabel:'Loading submission history'));}final rows=s.data!;if(rows.isEmpty)return const Center(child:Text('You have not submitted any responses yet.'));return RefreshIndicator(onRefresh:()async=>setState(()=>load=read()),child:ListView(children:rows.map((r)=>ListTile(title:Text(r['activity_title']??'Activity'),subtitle:Text('${r['status']} • ${participantDateTime(r['submitted_at']??r['updated_at'])}'))).toList()));}));}

class Messages extends StatefulWidget{const Messages({super.key,required this.api});final Api api;@override State<Messages>createState()=>_MessagesState();}class _MessagesState extends State<Messages>{late Future<List<dynamic>>load;@override void initState(){super.initState();load=read();}Future<List<dynamic>>read()async{try{final rows=await widget.api.messages();(await SharedPreferences.getInstance()).setString('cached_messages',jsonEncode(rows));return rows;}catch(_){final cached=await cachedList('cached_messages');if(cached!=null)return cached;rethrow;}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Messages')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Compose(api:widget.api))),label:const Text('Write message'),icon:const Icon(Icons.edit)),body:FutureBuilder<List<dynamic>>(future:load,builder:(c,s){if(!s.hasData){if(s.hasError)return Center(child:FilledButton(onPressed:()=>setState(()=>load=read()),child:const Text('Try again')));return const Center(child:CircularProgressIndicator(semanticsLabel:'Loading messages'));}final rows=s.data!;if(rows.isEmpty)return const Center(child:Text('You have no messages right now.'));return RefreshIndicator(onRefresh:()async=>setState(()=>load=read()),child:ListView(children:rows.map((m)=>Semantics(button:true,label:'Message from ${m['sender_type']=='researcher'?'your research team':'you'}, ${m['created_at']}',child:ListTile(title:Text(m['sender_type']=='researcher'?'Research team':'You'),subtitle:Text(m['body']??'',maxLines:2,overflow:TextOverflow.ellipsis),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>MessageDetail(message:Map<String,dynamic>.from(m))))))).toList()));}));}
class MessageDetail extends StatelessWidget{const MessageDetail({super.key,required this.message});final Map<String,dynamic>message;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Message')),body:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[Text(message['sender_type']=='researcher'?'Research team':'You',style:const TextStyle(fontWeight:FontWeight.bold)),Text(participantDateTime(message['created_at'])),const SizedBox(height:20),SelectableText(message['body']??'')])));}
class Compose extends StatefulWidget{const Compose({super.key,required this.api});final Api api;@override State<Compose>createState()=>_ComposeState();}class _ComposeState extends State<Compose>{final text=TextEditingController();bool sending=false;String? error;Future<void>send()async{final body=text.text.trim();if(body.isEmpty){setState(()=>error='Write a message before sending.');return;}setState(()=>sending=true);try{await widget.api.sendMessage(body,const Uuid().v4());if(mounted)Navigator.pop(context);}catch(_){setState(()=>error='We could not send your message. Please try again.');}if(mounted)setState(()=>sending=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Write message')),body:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Expanded(child:TextField(controller:text,maxLines:null,expands:true,decoration:const InputDecoration(labelText:'Your message',border:OutlineInputBorder()))),if(error!=null)Semantics(liveRegion:true,child:Text(error!,style:const TextStyle(color:Colors.red))),const SizedBox(height:12),SizedBox(height:48,child:FilledButton(onPressed:sending?null:send,child:Text(sending?'Sending…':'Send message')))])));}

class PhotoEvidence extends StatefulWidget{const PhotoEvidence({super.key,required this.api,required this.activityId});final Api api;final int activityId;@override State<PhotoEvidence>createState()=>_PhotoEvidenceState();}class _PhotoEvidenceState extends State<PhotoEvidence>{final picker=ImagePicker();XFile? photo;bool uploading=false;String status='';Future<void>choose(ImageSource source)async{try{final selected=await picker.pickImage(source:source,imageQuality:90);if(selected!=null)setState(()=>photo=selected);}catch(_){setState(()=>status='We could not open that photo source. Check your device permissions and try again.');}}Future<void>upload()async{if(photo==null)return;setState(()=>uploading=true);try{final result=await widget.api.uploadPhoto(widget.activityId,photo!,const Uuid().v4());final evidence=Map<String,dynamic>.from(result['evidence']);status=evidence['scan_status']=='clean'?'Photo uploaded and ready.':'Photo uploaded. It is being checked securely.';}catch(_){status='Your photo is still on this device. Please try uploading again.';}if(mounted)setState(()=>uploading=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Add photo evidence')),body:Padding(padding:const EdgeInsets.all(20),child:ListView(children:[const Text('Choose a photo to attach to this activity.'),const SizedBox(height:16),if(photo==null)...[SizedBox(height:48,child:FilledButton.icon(onPressed:()=>choose(ImageSource.camera),icon:const Icon(Icons.camera_alt),label:const Text('Take a photo'))),const SizedBox(height:12),SizedBox(height:48,child:OutlinedButton.icon(onPressed:()=>choose(ImageSource.gallery),icon:const Icon(Icons.photo_library),label:const Text('Choose from library')))]else...[Semantics(label:'Selected photo preview',image:true,child:Image.file(File(photo!.path),height:240,fit:BoxFit.contain)),Text(photo!.name),Row(children:[TextButton(onPressed:()=>setState(()=>photo=null),child:const Text('Remove photo')),TextButton(onPressed:()=>choose(ImageSource.camera),child:const Text('Retake'))]),SizedBox(height:48,child:FilledButton(onPressed:uploading?null:upload,child:Text(uploading?'Uploading…':'Upload photo')))],if(status.isNotEmpty)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.only(top:16),child:Text(status)))])));}

class DocumentEvidence extends StatefulWidget{const DocumentEvidence({super.key,required this.api,required this.activityId});final Api api;final int activityId;@override State<DocumentEvidence>createState()=>_DocumentEvidenceState();}class _DocumentEvidenceState extends State<DocumentEvidence>{PlatformFile? file;bool uploading=false;String status='';static const allowed={'pdf','doc','docx','txt','csv'};Future<void>choose()async{try{final result=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:allowed.toList(),withData:false);final selected=result?.files.single;if(selected!=null){if(selected.path==null||selected.size==0){setState(()=>status='Choose a valid document.');}else { setState(()=>file=selected); }}}catch(_){setState(()=>status='We could not open your files. Please try again.');}}Future<void>upload()async{if(file==null)return;setState(()=>uploading=true);try{final result=await widget.api.uploadDocument(widget.activityId,file!.path!,file!.name,const Uuid().v4());final evidence=Map<String,dynamic>.from(result['evidence']);status=evidence['scan_status']=='clean'?'Document uploaded and ready.':'Document uploaded. It is being checked securely.';}catch(_){status='Your document is still selected. Please try uploading again.';}if(mounted)setState(()=>uploading=false);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Add document evidence')),body:Padding(padding:const EdgeInsets.all(20),child:ListView(children:[const Text('Choose a PDF, Word, text or CSV document to attach to this activity.'),const SizedBox(height:16),if(file==null)SizedBox(height:48,child:FilledButton.icon(onPressed:choose,icon:const Icon(Icons.upload_file),label:const Text('Choose document')))else...[Semantics(label:'Selected document ${file!.name}, ${file!.size} bytes',child:ListTile(title:Text(file!.name),subtitle:Text('${(file!.size/1024).ceil()} KB'),leading:const Icon(Icons.description))),Row(children:[TextButton(onPressed:()=>setState(()=>file=null),child:const Text('Remove document')),TextButton(onPressed:choose,child:const Text('Choose another'))]),SizedBox(height:48,child:FilledButton(onPressed:uploading?null:upload,child:Text(uploading?'Uploading…':'Upload document')))],if(status.isNotEmpty)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.only(top:16),child:Text(status)))])));}

class VoiceDiary extends StatefulWidget{const VoiceDiary({super.key,required this.api,required this.activityId});final Api api;final int activityId;@override State<VoiceDiary>createState()=>_VoiceDiaryState();}class _VoiceDiaryState extends State<VoiceDiary>{final recorder=AudioRecorder(),player=AudioPlayer();String? path,status;bool recording=false,uploading=false;Future<void>toggle()async{if(recording){path=await recorder.stop();setState(()=>recording=false);return;}if(!await recorder.hasPermission()){setState(()=>status='Microphone permission is needed to record a voice diary.');return;}final dir=await getTemporaryDirectory();await recorder.start(const RecordConfig(encoder:AudioEncoder.aacLc),path:'${dir.path}/voice-diary.m4a');setState(()=>recording=true);}Future<void>play()async{if(path!=null)await player.play(DeviceFileSource(path!));}Future<void>upload()async{if(path==null)return;setState(()=>uploading=true);try{final r=await widget.api.uploadAudio(widget.activityId,path!,const Uuid().v4());final e=Map<String,dynamic>.from(r['evidence']);status=e['scan_status']=='clean'?'Voice diary uploaded and ready.':'Voice diary uploaded. It is being processed securely.';}catch(_){status='Your recording is still on this device. Please try uploading again.';}if(mounted)setState(()=>uploading=false);}@override void dispose(){recorder.dispose();player.dispose();super.dispose();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Voice diary')),body:Padding(padding:const EdgeInsets.all(20),child:ListView(children:[const Text('Record your thoughts, then listen back before you upload.'),const SizedBox(height:16),SizedBox(height:56,child:FilledButton.icon(onPressed:toggle,icon:Icon(recording?Icons.stop:Icons.mic),label:Text(recording?'Stop recording':'Start recording'))),if(path!=null)...[TextButton.icon(onPressed:play,icon:const Icon(Icons.play_arrow),label:const Text('Play recording')),TextButton(onPressed:()=>setState(()=>path=null),child:const Text('Delete recording')),SizedBox(height:48,child:FilledButton(onPressed:uploading?null:upload,child:Text(uploading?'Uploading…':'Upload voice diary')))],if(status!=null)Semantics(liveRegion:true,child:Padding(padding:const EdgeInsets.only(top:16),child:Text(status!)))])));}

class PrivacyChoices extends StatelessWidget{const PrivacyChoices({super.key,required this.api});final Api api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Privacy choices')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('You can ask to withdraw from this study or request deletion of your data. These requests are sent securely to Citizen Centric for processing.'),const SizedBox(height:20),SizedBox(height:52,child:OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PrivacyConfirm(api:api,deletion:false))),child:const Text('Withdraw from this study'))),const SizedBox(height:12),SizedBox(height:52,child:OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PrivacyConfirm(api:api,deletion:true))),child:const Text('Request data deletion')))]));}
class PrivacyConfirm extends StatefulWidget{const PrivacyConfirm({super.key,required this.api,required this.deletion});final Api api;final bool deletion;@override State<PrivacyConfirm>createState()=>_PrivacyConfirmState();}class _PrivacyConfirmState extends State<PrivacyConfirm>{bool agreed=false,sending=false;String? status;Future<void>send()async{setState(()=>sending=true);try{final r=widget.deletion?await widget.api.deletion(const Uuid().v4()):await widget.api.withdraw(const Uuid().v4());setState(()=>status=r['message']??'Your request has been received.');}catch(_){setState(()=>status='We could not send your request. Please try again.');}if(mounted)setState(()=>sending=false);}@override Widget build(BuildContext c){final title=widget.deletion?'Request data deletion':'Withdraw from this study';final detail=widget.deletion?'This sends a deletion request for review. It may not be processed immediately.':'This sends a withdrawal request for this study. You can cancel now without sending a request.';return Scaffold(appBar:AppBar(title:Text(title)),body:Padding(padding:const EdgeInsets.all(20),child:ListView(children:[Text(detail),CheckboxListTile(value:agreed,onChanged:(v)=>setState(()=>agreed=v??false),title:const Text('I understand and want to send this request.'),controlAffinity:ListTileControlAffinity.leading),if(status!=null)Semantics(liveRegion:true,child:Text(status!)),SizedBox(height:52,child:FilledButton(onPressed:agreed&&!sending?send:null,child:Text(sending?'Sending…':'Confirm request')))])));}}
